version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/preprocessed_unencoded:/app/backend/preprocessed_unencoded
      - ./model:/app/model
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ml-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
