services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - "5000:5000"
    volumes:
      # Mount only data directories, not the entire backend
      - ./backend/uploads:/app/backend/uploads
      - ./backend/preprocessed_unencoded:/app/backend/preprocessed_unencoded
      # Mount project_info for easy access to ProjectID_Detail.xlsx
      - ./notebooks/project_info:/app/backend/notebooks/project_info
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    container_name: ml-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    container_name: ml-frontend
    restart: unless-stopped

volumes:
  ml_uploads:
  ml_preprocessed:
  ml_models:
